export const formsConfig = [
  { id: "crimeData", title: "Crime Data" },
  { id: "nonbailableWarrants", title: "Non-Bailable Warrants" },
  { id: "actProposals", title: "PD Act Proposals" },
  { id: "externmentActions", title: "Externment Actions" },
  { id: "sensitivePoliticalCases", title: "Sensitive / Political Cases" },
  { id: "vcProductions", title: "VC Productions" },
  { id: "importantCases", title: "Important Cases" },
  { id: "cctvSurveillance", title: "CCTV Surveillance" },
  { id: "cyberCrimeMonitoring", title: "Cyber Crime Monitoring" },
  { id: "womensSafety", title: "Women’s Safety" },
  { id: "focusArea", title: "Focus Area" },
  { id: "legalMonitoring", title: "Legal Monitoring" },
  { id: "dsrSummary", title: "DSR Summary" },
  { id: "fertilizerMonitoring", title: "Fertilizer Monitoring" },
  { id: "disasterResponse", title: "Disaster / Emergency Response" },
  { id: "publicFeedback", title: "Public Feedback" },
];
